# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ping.proto for package 'ping'

require 'grpc'
require 'ping_pb'

module Ping
  module PingService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'ping.PingService'

      rpc :Ping, ::Ping::Empty, ::Ping::Pong
      rpc :PingStream, ::Ping::PingRequest, stream(::Ping::Pong)
    end

    Stub = Service.rpc_stub_class
  end
end
