# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ping.proto", :syntax => :proto3) do
    add_message "ping.Empty" do
    end
    add_message "ping.PingRequest" do
      optional :count, :int32, 1
    end
    add_message "ping.Pong" do
      optional :text, :string, 1
    end
  end
end

module Ping
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ping.Empty").msgclass
  PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ping.PingRequest").msgclass
  Pong = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ping.Pong").msgclass
end
